import { PrismaClient, StatementType, ValueNature } from "@prisma/client";
const prisma = new PrismaClient();
type AccountSeed = [string, string, StatementType, ValueNature, number];
const accounts: AccountSeed[] = [
["REV","Revenue",StatementType.INCOME_STATEMENT,ValueNature.FLOW,100],["COGS","Cost of Goods Sold",StatementType.INCOME_STATEMENT,ValueNature.FLOW,110],["GROSS_PROFIT","Gross Profit",StatementType.INCOME_STATEMENT,ValueNature.FLOW,120],["SGA","Selling, General and Administrative Expense",StatementType.INCOME_STATEMENT,ValueNature.FLOW,130],["OPERATING_PROFIT","Operating Profit / EBIT",StatementType.INCOME_STATEMENT,ValueNature.FLOW,140],["EBITDA","EBITDA",StatementType.INCOME_STATEMENT,ValueNature.FLOW,150],["FINANCE_INCOME","Finance Income",StatementType.INCOME_STATEMENT,ValueNature.FLOW,160],["FINANCE_COST","Finance Cost",StatementType.INCOME_STATEMENT,ValueNature.FLOW,170],["FX_GAIN_LOSS","Foreign Exchange Gain / Loss",StatementType.INCOME_STATEMENT,ValueNature.FLOW,180],["PRETAX_PROFIT","Profit Before Tax",StatementType.INCOME_STATEMENT,ValueNature.FLOW,190],["TAX_EXPENSE","Income Tax Expense",StatementType.INCOME_STATEMENT,ValueNature.FLOW,200],["NET_PROFIT","Net Profit",StatementType.INCOME_STATEMENT,ValueNature.FLOW,210],["NET_PROFIT_PARENT","Net Profit Attributable to Owners of Parent",StatementType.INCOME_STATEMENT,ValueNature.FLOW,220],["EPS_BASIC","Basic Earnings per Share",StatementType.INCOME_STATEMENT,ValueNature.PER_SHARE,230],["EPS_DILUTED","Diluted Earnings per Share",StatementType.INCOME_STATEMENT,ValueNature.PER_SHARE,240],
["CASH","Cash and Cash Equivalents",StatementType.BALANCE_SHEET,ValueNature.STOCK,300],["SHORT_TERM_INVESTMENTS","Short-term Investments",StatementType.BALANCE_SHEET,ValueNature.STOCK,310],["AR","Accounts Receivable",StatementType.BALANCE_SHEET,ValueNature.STOCK,320],["OTHER_RECEIVABLES","Other Receivables",StatementType.BALANCE_SHEET,ValueNature.STOCK,330],["INV","Inventory",StatementType.BALANCE_SHEET,ValueNature.STOCK,340],["CURRENT_ASSETS","Total Current Assets",StatementType.BALANCE_SHEET,ValueNature.STOCK,350],["PPE","Property, Plant and Equipment",StatementType.BALANCE_SHEET,ValueNature.STOCK,360],["RIGHT_OF_USE_ASSETS","Right-of-use Assets",StatementType.BALANCE_SHEET,ValueNature.STOCK,370],["GOODWILL","Goodwill",StatementType.BALANCE_SHEET,ValueNature.STOCK,380],["INTANGIBLE_ASSETS","Intangible Assets",StatementType.BALANCE_SHEET,ValueNature.STOCK,390],["LONG_TERM_INVESTMENTS","Long-term Investments",StatementType.BALANCE_SHEET,ValueNature.STOCK,400],["TOTAL_ASSETS","Total Assets",StatementType.BALANCE_SHEET,ValueNature.STOCK,410],["AP","Accounts Payable",StatementType.BALANCE_SHEET,ValueNature.STOCK,420],["SHORT_TERM_DEBT","Short-term Debt",StatementType.BALANCE_SHEET,ValueNature.STOCK,430],["CURRENT_LIAB","Total Current Liabilities",StatementType.BALANCE_SHEET,ValueNature.STOCK,440],["LONG_TERM_DEBT","Long-term Debt",StatementType.BALANCE_SHEET,ValueNature.STOCK,450],["LEASE_LIABILITIES","Lease Liabilities",StatementType.BALANCE_SHEET,ValueNature.STOCK,460],["TOTAL_DEBT","Total Debt",StatementType.BALANCE_SHEET,ValueNature.STOCK,470],["TOTAL_LIAB","Total Liabilities",StatementType.BALANCE_SHEET,ValueNature.STOCK,480],["EQUITY","Total Equity",StatementType.BALANCE_SHEET,ValueNature.STOCK,490],["EQUITY_PARENT","Equity Attributable to Owners of Parent",StatementType.BALANCE_SHEET,ValueNature.STOCK,500],["RETAINED_EARNINGS","Retained Earnings",StatementType.BALANCE_SHEET,ValueNature.STOCK,510],
["OCF","Operating Cash Flow",StatementType.CASH_FLOW,ValueNature.FLOW,600],["CAPEX","Capital Expenditure",StatementType.CASH_FLOW,ValueNature.FLOW,610],["ICF","Investing Cash Flow",StatementType.CASH_FLOW,ValueNature.FLOW,620],["CFF","Financing Cash Flow",StatementType.CASH_FLOW,ValueNature.FLOW,630],["DIVIDENDS_PAID","Dividends Paid",StatementType.CASH_FLOW,ValueNature.FLOW,640],["DEBT_ISSUED","Debt Issued",StatementType.CASH_FLOW,ValueNature.FLOW,650],["DEBT_REPAID","Debt Repaid",StatementType.CASH_FLOW,ValueNature.FLOW,660],["FCF","Free Cash Flow",StatementType.CASH_FLOW,ValueNature.FLOW,670],["NET_CHANGE_CASH","Net Change in Cash",StatementType.CASH_FLOW,ValueNature.FLOW,680]];

const IFRS_PRESENTATION={label:"IFRS Foundation — IAS 1 Presentation of Financial Statements",url:"https://www.ifrs.org/issued-standards/list-of-standards/ias-1-presentation-of-financial-statements/"};
const IFRS_CASHFLOW={label:"IFRS Foundation — IAS 7 Statement of Cash Flows",url:"https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-of-cash-flows/"};
const IFRS_INVENTORY={label:"IFRS Foundation — IAS 2 Inventories",url:"https://www.ifrs.org/issued-standards/list-of-standards/ias-2-inventories/"};
const IFRS_PPE={label:"IFRS Foundation — IAS 16 Property, Plant and Equipment",url:"https://www.ifrs.org/issued-standards/list-of-standards/ias-16-property-plant-and-equipment/"};
const IFRS_REVENUE={label:"IFRS Foundation — IFRS 15 Revenue from Contracts with Customers",url:"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-15-revenue-from-contracts-with-customers/"};
const IFRS_FINANCIAL={label:"IFRS Foundation — IFRS 9 Financial Instruments",url:"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-9-financial-instruments/"};
const IFRS_LEASES={label:"IFRS Foundation — IFRS 16 Leases",url:"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-16-leases/"};
const IFRS_INTANGIBLE={label:"IFRS Foundation — IAS 38 Intangible Assets",url:"https://www.ifrs.org/issued-standards/list-of-standards/ias-38-intangible-assets/"};
const IFRS_COMBINATIONS={label:"IFRS Foundation — IFRS 3 Business Combinations",url:"https://www.ifrs.org/issued-standards/list-of-standards/ifrs-3-business-combinations/"};
type Knowledge={displayNameId:string;definition:string;investorMeaning:string;aliases:string[];relatedMetrics:string[];positiveSignals:string[];redFlags:string[];sourceRefs:{label:string;url:string}[]};
const knowledge:Record<string,Knowledge>={
REV:{displayNameId:"Pendapatan / Penjualan",definition:"Pendapatan yang diakui dari penyerahan barang atau jasa kepada pelanggan sesuai aktivitas utama perusahaan.",investorMeaning:"Fondasi pertumbuhan bisnis. Bedakan pertumbuhan dari volume, harga, akuisisi, atau faktor sementara.",aliases:["pendapatan","penjualan","penjualan neto","net sales","sales","revenue"],relatedMetrics:["Revenue Growth","Gross Margin","Receivable Days","CAGR"],positiveSignals:["Revenue tumbuh konsisten bersama arus kas operasi."],redFlags:["Revenue tumbuh tetapi piutang tumbuh jauh lebih cepat.","Pertumbuhan tinggi tidak diikuti gross profit atau cash flow."],sourceRefs:[IFRS_REVENUE]},
COGS:{displayNameId:"Beban Pokok Penjualan",definition:"Biaya yang secara langsung berkaitan dengan barang atau jasa yang menghasilkan pendapatan pada periode tersebut.",investorMeaning:"Perubahan COGS relatif terhadap revenue menentukan arah gross margin.",aliases:["beban pokok penjualan","harga pokok penjualan","cost of sales","cost of goods sold","HPP"],relatedMetrics:["Gross Profit","Gross Margin","Inventory Turnover"],positiveSignals:["COGS tumbuh lebih lambat dari revenue sehingga gross margin membaik."],redFlags:["COGS tumbuh lebih cepat daripada revenue secara persisten."],sourceRefs:[IFRS_INVENTORY,IFRS_PRESENTATION]},
GROSS_PROFIT:{displayNameId:"Laba Kotor",definition:"Selisih antara pendapatan dan beban pokok penjualan.",investorMeaning:"Ukuran awal pricing power dan efisiensi produksi/pengadaan.",aliases:["laba bruto","laba kotor","gross profit"],relatedMetrics:["Gross Margin","Revenue Growth"],positiveSignals:["Gross margin stabil atau meningkat bersama pertumbuhan revenue."],redFlags:["Revenue tumbuh tetapi gross margin terus turun."],sourceRefs:[IFRS_PRESENTATION]},
OPERATING_PROFIT:{displayNameId:"Laba Operasi / EBIT",definition:"Laba dari kegiatan operasi sebelum dampak pembiayaan dan pajak.",investorMeaning:"Menilai profitabilitas bisnis inti tanpa tercampur struktur utang dan pajak.",aliases:["laba usaha","laba operasi","operating profit","EBIT"],relatedMetrics:["Operating Margin","ROIC","Interest Coverage"],positiveSignals:["Operating profit tumbuh lebih cepat dari revenue secara sehat."],redFlags:["Margin operasi turun terus meski revenue meningkat."],sourceRefs:[IFRS_PRESENTATION]},
NET_PROFIT:{displayNameId:"Laba Bersih",definition:"Laba setelah memperhitungkan seluruh pendapatan, beban, pembiayaan, dan pajak pada periode berjalan.",investorMeaning:"Kualitas laba harus dikonfirmasi dengan arus kas dan item non-recurring.",aliases:["laba tahun berjalan","laba bersih","net income","profit for the year","net profit"],relatedMetrics:["Net Margin","ROE","EPS","OCF / Net Profit"],positiveSignals:["Laba tumbuh bersama operating cash flow."],redFlags:["Laba naik tetapi operating cash flow lemah atau negatif."],sourceRefs:[IFRS_PRESENTATION]},
CASH:{displayNameId:"Kas dan Setara Kas",definition:"Kas dan investasi jangka sangat pendek yang sangat likuid.",investorMeaning:"Bantalan likuiditas yang harus dibandingkan dengan utang dan kebutuhan modal kerja.",aliases:["kas","kas dan setara kas","cash","cash equivalents"],relatedMetrics:["Net Debt","Current Ratio","Cash Runway"],positiveSignals:["Kas memadai dibanding kewajiban jangka pendek dan kebutuhan operasi."],redFlags:["Kas turun cepat sementara utang meningkat."],sourceRefs:[IFRS_CASHFLOW]},
AR:{displayNameId:"Piutang Usaha",definition:"Hak kontraktual perusahaan untuk menerima kas dari pelanggan atas barang atau jasa yang telah diberikan.",investorMeaning:"Menguji kualitas pertumbuhan penjualan dan kemampuan menagih pelanggan.",aliases:["piutang usaha","piutang dagang","trade receivables","accounts receivable","receivables"],relatedMetrics:["Receivable Days / DSO","Cash Conversion Cycle","OCF vs Net Profit","Allowance / ECL"],positiveSignals:["Piutang tumbuh sejalan atau lebih lambat dari revenue.","DSO stabil atau membaik."],redFlags:["Piutang tumbuh jauh lebih cepat daripada revenue.","DSO meningkat terus atau allowance/ECL melonjak."],sourceRefs:[IFRS_FINANCIAL]},
INV:{displayNameId:"Persediaan",definition:"Aset berupa barang untuk dijual, dalam proses produksi, atau bahan/perlengkapan untuk produksi atau jasa.",investorMeaning:"Menunjukkan modal yang tertahan dalam stok dan risiko perubahan permintaan atau obsolete.",aliases:["persediaan","inventory","inventories","stok"],relatedMetrics:["Inventory Days","Inventory Turnover","Cash Conversion Cycle","Gross Margin"],positiveSignals:["Inventory tumbuh sejalan dengan penjualan dan turnover stabil."],redFlags:["Inventory naik jauh lebih cepat dari revenue.","Inventory days meningkat terus dan margin melemah."],sourceRefs:[IFRS_INVENTORY]},
PPE:{displayNameId:"Aset Tetap / Properti, Pabrik dan Peralatan",definition:"Aset berwujud yang digunakan dalam produksi, jasa, penyewaan, atau administrasi lebih dari satu periode.",investorMeaning:"Pertumbuhan PPE harus dinilai bersama kapasitas, revenue, ROIC, depreciation, dan capex.",aliases:["aset tetap","property plant equipment","PPE","fixed assets"],relatedMetrics:["Asset Turnover","ROIC","CAPEX / Sales","Depreciation"],positiveSignals:["Investasi aset menghasilkan pertumbuhan kapasitas, revenue, dan return yang memadai."],redFlags:["Capex/PPE besar tetapi utilisasi, revenue atau ROIC tidak membaik."],sourceRefs:[IFRS_PPE]},
GOODWILL:{displayNameId:"Goodwill",definition:"Aset yang timbul dalam kombinasi bisnis dari manfaat ekonomi masa depan yang tidak dapat diidentifikasi secara individual.",investorMeaning:"Sering mencerminkan premi akuisisi dan perlu diuji terhadap return serta risiko impairment.",aliases:["goodwill","muhibah"],relatedMetrics:["Goodwill / Equity","ROIC","Acquisition Return","Impairment"],positiveSignals:["Bisnis hasil akuisisi menghasilkan cash flow dan return sesuai ekspektasi."],redFlags:["Goodwill sangat besar terhadap equity.","Akuisisi berulang diikuti impairment besar."],sourceRefs:[IFRS_COMBINATIONS]},
RIGHT_OF_USE_ASSETS:{displayNameId:"Aset Hak Guna",definition:"Aset yang merepresentasikan hak lessee untuk menggunakan aset pendasar selama masa sewa.",investorMeaning:"Menunjukkan aset ekonomi dari kontrak sewa.",aliases:["aset hak guna","right of use asset","ROU asset"],relatedMetrics:["Lease Liabilities","Adjusted Debt","EBITDA"],positiveSignals:["Kewajiban sewa sejalan dengan kapasitas menghasilkan cash flow."],redFlags:["Komitmen sewa meningkat cepat tanpa pertumbuhan operasi yang sepadan."],sourceRefs:[IFRS_LEASES]},
INTANGIBLE_ASSETS:{displayNameId:"Aset Takberwujud",definition:"Aset nonmoneter teridentifikasi tanpa wujud fisik.",investorMeaning:"Bedakan aset produktif dari kapitalisasi biaya yang dapat mempercantik laba jangka pendek.",aliases:["aset takberwujud","aset tidak berwujud","intangible assets","software","license"],relatedMetrics:["ROIC","Amortisation","Intangible Assets / Equity"],positiveSignals:["Aset intangible mendukung pertumbuhan cash flow dan return."],redFlags:["Kapitalisasi intangible meningkat cepat sementara cash flow lemah."],sourceRefs:[IFRS_INTANGIBLE]},
TOTAL_DEBT:{displayNameId:"Total Utang Berbunga",definition:"Agregasi kewajiban pembiayaan berbunga jangka pendek dan jangka panjang untuk analisis leverage.",investorMeaning:"Menentukan risiko finansial dan sensitivitas terhadap suku bunga, refinancing, dan penurunan cash flow.",aliases:["total debt","utang berbunga","pinjaman","borrowings","bank loans"],relatedMetrics:["Net Debt","Debt / EBITDA","Debt / Equity","Interest Coverage"],positiveSignals:["Debt tumbuh lebih lambat dari cash flow dan leverage menurun."],redFlags:["Debt naik cepat saat operating cash flow melemah."],sourceRefs:[IFRS_FINANCIAL]},
OCF:{displayNameId:"Arus Kas Operasi",definition:"Arus kas dari aktivitas penghasil pendapatan utama perusahaan dan aktivitas lain yang bukan investasi atau pendanaan.",investorMeaning:"Pemeriksaan penting atas kualitas laba karena menunjukkan kas yang dihasilkan operasi.",aliases:["arus kas operasi","cash flow from operations","operating cash flow","CFO","OCF"],relatedMetrics:["OCF / Net Profit","Cash Conversion","Free Cash Flow","Cash Conversion Cycle"],positiveSignals:["OCF konsisten positif dan sejalan atau lebih kuat daripada laba."],redFlags:["Net profit positif tetapi OCF terus lemah atau negatif."],sourceRefs:[IFRS_CASHFLOW]},
CAPEX:{displayNameId:"Belanja Modal / Capital Expenditure",definition:"Pengeluaran untuk memperoleh atau meningkatkan aset jangka panjang.",investorMeaning:"Pisahkan maintenance dan growth capex untuk menilai reinvestasi dan free cash flow.",aliases:["belanja modal","capital expenditure","capex","purchase of fixed assets","acquisition of PPE"],relatedMetrics:["CAPEX / Sales","FCF","Asset Turnover","ROIC"],positiveSignals:["Capex menghasilkan pertumbuhan kapasitas dan return di atas cost of capital."],redFlags:["Capex tinggi berulang tetapi revenue, cash flow, atau ROIC stagnan."],sourceRefs:[IFRS_CASHFLOW,IFRS_PPE]},
FCF:{displayNameId:"Arus Kas Bebas / Free Cash Flow",definition:"Metrik analitis InvestAI yang umumnya menghitung kas operasi setelah belanja modal.",investorMeaning:"Menunjukkan kas tersisa setelah kebutuhan investasi utama.",aliases:["free cash flow","arus kas bebas","FCF"],relatedMetrics:["FCF Margin","FCF Yield","OCF","CAPEX"],positiveSignals:["FCF positif dan bertumbuh secara berkelanjutan."],redFlags:["Laba meningkat tetapi FCF negatif berkepanjangan tanpa alasan ekspansi yang menghasilkan return."],sourceRefs:[IFRS_CASHFLOW]}
};

const accountSpecificGuidance:Record<string,{displayNameId:string;positive:string[];red:string[];metrics:string[]}>= {
SGA:{displayNameId:"Beban Penjualan, Umum & Administrasi",positive:["SG&A tumbuh lebih lambat dari revenue sehingga operating leverage membaik."],red:["SG&A tumbuh jauh lebih cepat dari revenue tanpa peningkatan pertumbuhan atau profitabilitas."],metrics:["SG&A / Revenue","Operating Margin"]},
EBITDA:{displayNameId:"EBITDA",positive:["EBITDA tumbuh bersama revenue dan arus kas operasi."],red:["EBITDA meningkat tetapi OCF melemah atau kebutuhan capex sangat tinggi."],metrics:["EBITDA Margin","Debt / EBITDA","OCF"]},
FINANCE_INCOME:{displayNameId:"Pendapatan Keuangan",positive:["Pendapatan keuangan berasal dari likuiditas produktif dan berulang secara wajar."],red:["Laba sangat bergantung pada pendapatan keuangan non-operasional atau tidak berulang."],metrics:["Finance Income / Pretax Profit","Cash"]},
FINANCE_COST:{displayNameId:"Beban Keuangan",positive:["Beban bunga terkendali dan interest coverage membaik."],red:["Beban keuangan naik lebih cepat dari laba operasi atau interest coverage memburuk."],metrics:["Interest Coverage","Finance Cost / EBIT"]},
FX_GAIN_LOSS:{displayNameId:"Laba / Rugi Selisih Kurs",positive:["Eksposur kurs terkendali dan tidak mendominasi laba."],red:["Laba sangat volatil karena selisih kurs atau rugi kurs berulang besar."],metrics:["FX Gain/Loss / Pretax Profit","Foreign Currency Debt"]},
PRETAX_PROFIT:{displayNameId:"Laba Sebelum Pajak",positive:["Laba sebelum pajak tumbuh sejalan dengan laba operasi."],red:["Laba sebelum pajak naik terutama karena item non-operasional sementara."],metrics:["Pretax Margin","Operating Profit"]},
TAX_EXPENSE:{displayNameId:"Beban Pajak Penghasilan",positive:["Effective tax rate relatif stabil dan dapat dijelaskan."],red:["Effective tax rate sangat volatil atau laba ditopang manfaat pajak yang tidak berulang."],metrics:["Effective Tax Rate","Pretax Profit"]},
NET_PROFIT_PARENT:{displayNameId:"Laba Bersih Pemilik Entitas Induk",positive:["Laba yang dapat diatribusikan ke pemegang saham induk tumbuh bersama cash flow."],red:["Laba konsolidasi tumbuh tetapi porsi untuk pemilik induk melemah signifikan."],metrics:["EPS","ROE","OCF / Net Profit"]},
EPS_BASIC:{displayNameId:"Laba per Saham Dasar",positive:["EPS tumbuh bersama laba dan tanpa kenaikan jumlah saham yang merugikan pemegang saham."],red:["Laba naik tetapi EPS stagnan/turun karena dilusi saham."],metrics:["EPS Growth","Share Count","P/E"]},
EPS_DILUTED:{displayNameId:"Laba per Saham Dilusian",positive:["Perbedaan EPS diluted dan basic kecil serta stabil."],red:["EPS diluted jauh di bawah EPS basic, menandakan potensi dilusi material."],metrics:["Dilution","EPS Growth"]},
SHORT_TERM_INVESTMENTS:{displayNameId:"Investasi Jangka Pendek",positive:["Investasi jangka pendek likuid dan mendukung pengelolaan kas."],red:["Nilainya besar tetapi kualitas, likuiditas, atau risiko nilainya tidak jelas."],metrics:["Cash + Short-term Investments","Current Ratio"]},
OTHER_RECEIVABLES:{displayNameId:"Piutang Lain-lain",positive:["Piutang lain-lain kecil, stabil, dan dapat dijelaskan."],red:["Piutang lain-lain melonjak atau material tanpa penjelasan bisnis yang jelas."],metrics:["Other Receivables / Assets","Receivable Growth"]},
CURRENT_ASSETS:{displayNameId:"Total Aset Lancar",positive:["Aset lancar cukup untuk mendukung modal kerja dan kewajiban jangka pendek."],red:["Aset lancar naik terutama karena piutang atau inventory yang menumpuk, bukan kas."],metrics:["Current Ratio","Quick Ratio","Working Capital"]},
LONG_TERM_INVESTMENTS:{displayNameId:"Investasi Jangka Panjang",positive:["Investasi menghasilkan return atau nilai strategis yang terukur."],red:["Investasi besar berulang tidak menghasilkan cash return atau memicu impairment."],metrics:["Investment Return","ROIC","Impairment"]},
TOTAL_ASSETS:{displayNameId:"Total Aset",positive:["Pertumbuhan aset diikuti revenue, laba, dan return on assets yang sehat."],red:["Aset tumbuh cepat tetapi revenue, cash flow, atau ROA stagnan."],metrics:["ROA","Asset Turnover","Asset Growth"]},
AP:{displayNameId:"Utang Usaha",positive:["Utang usaha tumbuh sejalan dengan aktivitas operasi dan hubungan pemasok tetap sehat."],red:["Payable days melonjak tajam karena tekanan likuiditas atau pembayaran pemasok tertunda."],metrics:["Payable Days / DPO","Cash Conversion Cycle"]},
SHORT_TERM_DEBT:{displayNameId:"Utang Jangka Pendek",positive:["Utang jangka pendek dapat ditutup oleh kas dan cash flow operasi."],red:["Utang jangka pendek melonjak sementara kas/OCF melemah, meningkatkan refinancing risk."],metrics:["Current Ratio","Net Debt","Short-term Debt / Cash"]},
CURRENT_LIAB:{displayNameId:"Total Liabilitas Jangka Pendek",positive:["Kewajiban lancar terkelola dengan likuiditas dan cash conversion yang sehat."],red:["Liabilitas lancar tumbuh jauh lebih cepat daripada aset lancar dan OCF."],metrics:["Current Ratio","Quick Ratio","Working Capital"]},
LONG_TERM_DEBT:{displayNameId:"Utang Jangka Panjang",positive:["Utang jangka panjang mendanai aset produktif dan leverage tetap terkendali."],red:["Utang jangka panjang meningkat tanpa pertumbuhan EBITDA/OCF yang sepadan."],metrics:["Debt / EBITDA","Interest Coverage","Net Debt"]},
LEASE_LIABILITIES:{displayNameId:"Liabilitas Sewa",positive:["Liabilitas sewa sejalan dengan aset hak guna dan kemampuan menghasilkan cash flow."],red:["Komitmen sewa meningkat cepat dan menambah fixed obligations saat cash flow melemah."],metrics:["Lease Liabilities / EBITDA","Adjusted Debt"]},
TOTAL_LIAB:{displayNameId:"Total Liabilitas",positive:["Pertumbuhan liabilitas lebih lambat dari aset produktif dan cash flow."],red:["Liabilitas tumbuh cepat sementara equity atau cash flow melemah."],metrics:["Liabilities / Assets","Debt / Equity"]},
EQUITY:{displayNameId:"Total Ekuitas",positive:["Ekuitas tumbuh terutama dari laba ditahan dan return on equity sehat."],red:["Ekuitas turun karena rugi, impairment, atau distribusi melebihi kemampuan menghasilkan laba."],metrics:["ROE","Debt / Equity","Book Value Growth"]},
EQUITY_PARENT:{displayNameId:"Ekuitas Pemilik Entitas Induk",positive:["Ekuitas pemilik induk tumbuh bersama laba yang dapat diatribusikan kepada pemegang saham."],red:["Ekuitas konsolidasi tumbuh tetapi porsi pemilik induk melemah material."],metrics:["Book Value per Share","ROE"]},
RETAINED_EARNINGS:{displayNameId:"Saldo Laba",positive:["Saldo laba tumbuh konsisten dari profit yang dipertahankan dan produktif."],red:["Saldo laba menurun terus akibat rugi atau distribusi yang tidak berkelanjutan."],metrics:["Retained Earnings Growth","ROE","Dividend Payout"]},
ICF:{displayNameId:"Arus Kas Investasi",positive:["Arus kas investasi negatif terutama untuk capex produktif dengan return yang baik."],red:["Cash outflow investasi besar berulang tanpa peningkatan kapasitas, revenue, atau return."],metrics:["CAPEX","FCF","ROIC"]},
CFF:{displayNameId:"Arus Kas Pendanaan",positive:["Pendanaan digunakan disiplin dan struktur modal membaik."],red:["Perusahaan terus bergantung pada utang atau penerbitan saham untuk menutup operasi."],metrics:["Net Debt","Share Count","FCF"]},
DIVIDENDS_PAID:{displayNameId:"Dividen Dibayar",positive:["Dividen ditopang FCF dan payout ratio yang berkelanjutan."],red:["Dividen dibayar dengan menambah utang atau saat FCF konsisten negatif."],metrics:["Dividend Payout","FCF Coverage","Dividend Yield"]},
DEBT_ISSUED:{displayNameId:"Penerbitan / Penarikan Utang",positive:["Utang baru mendanai investasi dengan return yang memadai atau refinancing yang lebih baik."],red:["Utang baru berulang digunakan menutup kekurangan kas operasi."],metrics:["Net Debt","Debt / EBITDA","ROIC"]},
DEBT_REPAID:{displayNameId:"Pembayaran Utang",positive:["Pembayaran utang menurunkan leverage tanpa mengganggu kebutuhan operasi."],red:["Pembayaran utang menguras kas karena perusahaan tidak menghasilkan FCF yang cukup."],metrics:["Net Debt","FCF","Liquidity"]},
NET_CHANGE_CASH:{displayNameId:"Perubahan Bersih Kas",positive:["Kas meningkat dari operasi yang sehat, bukan terutama dari penambahan utang."],red:["Kas meningkat hanya karena utang/equity baru atau terus turun akibat operasi negatif."],metrics:["OCF","CFF","Cash Balance"]}
};
function baselineKnowledge(code:string,name:string,statementType:StatementType):Knowledge{
 const g=accountSpecificGuidance[code]; const cashFlow=statementType===StatementType.CASH_FLOW;
 return {displayNameId:g?.displayNameId??name,definition:`${name} adalah akun ${cashFlow?"arus kas":"laporan keuangan"} yang perlu dibaca bersama tren historis, catatan laporan keuangan, dan akun terkait.`,investorMeaning:"InvestAI menggunakannya sebagai bagian dari analisis tren, kualitas laba, likuiditas, leverage, dan return. Sinyal tidak boleh dinilai sendirian tanpa konteks perusahaan.",aliases:[name,code],relatedMetrics:g?.metrics??["Historical Trend","YoY Growth"],positiveSignals:g?.positive??["Tren akun konsisten dengan pertumbuhan bisnis dan cash flow yang sehat."],redFlags:g?.red??["Perubahan akun material tidak sejalan dengan revenue, laba, atau cash flow dan tidak memiliki penjelasan ekonomi yang jelas."],sourceRefs:[cashFlow?IFRS_CASHFLOW:IFRS_PRESENTATION]};
}
async function main(){
 for(const [code,name,statementType,valueNature,sortOrder] of accounts){const k=knowledge[code]??baselineKnowledge(code,name,statementType);await prisma.canonicalAccount.upsert({where:{code},update:{name,statementType,valueNature,sortOrder,isActive:true,...k},create:{code,name,statementType,valueNature,sortOrder,...k}});}
 for(const company of [{ticker:"ICBP",name:"Indofood CBP Sukses Makmur Tbk",sector:"Consumer Non-Cyclicals",subsector:"Processed Foods"},{ticker:"BTPS",name:"Bank BTPN Syariah Tbk",sector:"Financials",subsector:"Banks"},{ticker:"SMRA",name:"Summarecon Agung Tbk",sector:"Properties",subsector:"Real Estate"},{ticker:"MEDC",name:"Medco Energi Internasional Tbk",sector:"Energy",subsector:"Oil & Gas",currency:"USD"},{ticker:"POWR",name:"Cikarang Listrindo Tbk",sector:"Utilities",subsector:"Independent Power Producer"}])await prisma.company.upsert({where:{ticker:company.ticker},update:company,create:company});
 console.log(`Seeded ${accounts.length} canonical accounts with complete investor dictionary coverage.`);
}
main().catch((e)=>{console.error(e);process.exit(1)}).finally(()=>prisma.$disconnect());