import { PrismaClient, StatementType, ValueNature } from "@prisma/client";

const prisma = new PrismaClient();
type AccountSeed = [string, string, StatementType, ValueNature, number];
type Ref = { label: string; url: string };
type Knowledge = {
  displayNameId: string;
  definition: string;
  investorMeaning: string;
  aliases: string[];
  relatedMetrics: string[];
  positiveSignals: string[];
  redFlags: string[];
  sourceRefs: Ref[];
};

const accounts: AccountSeed[] = [
  ["REV","Revenue",StatementType.INCOME_STATEMENT,ValueNature.FLOW,100],
  ["COGS","Cost of Goods Sold",StatementType.INCOME_STATEMENT,ValueNature.FLOW,110],
  ["GROSS_PROFIT","Gross Profit",StatementType.INCOME_STATEMENT,ValueNature.FLOW,120],
  ["SGA","Selling, General and Administrative Expense",StatementType.INCOME_STATEMENT,ValueNature.FLOW,130],
  ["OPERATING_PROFIT","Operating Profit / EBIT",StatementType.INCOME_STATEMENT,ValueNature.FLOW,140],
  ["EBITDA","EBITDA",StatementType.INCOME_STATEMENT,ValueNature.FLOW,150],
  ["FINANCE_INCOME","Finance Income",StatementType.INCOME_STATEMENT,ValueNature.FLOW,160],
  ["FINANCE_COST","Finance Cost",StatementType.INCOME_STATEMENT,ValueNature.FLOW,170],
  ["FX_GAIN_LOSS","Foreign Exchange Gain / Loss",StatementType.INCOME_STATEMENT,ValueNature.FLOW,180],
  ["PRETAX_PROFIT","Profit Before Tax",StatementType.INCOME_STATEMENT,ValueNature.FLOW,190],
  ["TAX_EXPENSE","Income Tax Expense",StatementType.INCOME_STATEMENT,ValueNature.FLOW,200],
  ["NET_PROFIT","Net Profit",StatementType.INCOME_STATEMENT,ValueNature.FLOW,210],
  ["NET_PROFIT_PARENT","Net Profit Attributable to Owners of Parent",StatementType.INCOME_STATEMENT,ValueNature.FLOW,220],
  ["EPS_BASIC","Basic Earnings per Share",StatementType.INCOME_STATEMENT,ValueNature.PER_SHARE,230],
  ["EPS_DILUTED","Diluted Earnings per Share",StatementType.INCOME_STATEMENT,ValueNature.PER_SHARE,240],
  ["CASH","Cash and Cash Equivalents",StatementType.BALANCE_SHEET,ValueNature.STOCK,300],
  ["SHORT_TERM_INVESTMENTS","Short-term Investments",StatementType.BALANCE_SHEET,ValueNature.STOCK,310],
  ["AR","Accounts Receivable",StatementType.BALANCE_SHEET,ValueNature.STOCK,320],
  ["OTHER_RECEIVABLES","Other Receivables",StatementType.BALANCE_SHEET,ValueNature.STOCK,330],
  ["INV","Inventory",StatementType.BALANCE_SHEET,ValueNature.STOCK,340],
  ["CURRENT_ASSETS","Total Current Assets",StatementType.BALANCE_SHEET,ValueNature.STOCK,350],
  ["PPE","Property, Plant and Equipment",StatementType.BALANCE_SHEET,ValueNature.STOCK,360],
  ["RIGHT_OF_USE_ASSETS","Right-of-use Assets",StatementType.BALANCE_SHEET,ValueNature.STOCK,370],
  ["GOODWILL","Goodwill",StatementType.BALANCE_SHEET,ValueNature.STOCK,380],
  ["INTANGIBLE_ASSETS","Intangible Assets",StatementType.BALANCE_SHEET,ValueNature.STOCK,390],
  ["LONG_TERM_INVESTMENTS","Long-term Investments",StatementType.BALANCE_SHEET,ValueNature.STOCK,400],
  ["TOTAL_ASSETS","Total Assets",StatementType.BALANCE_SHEET,ValueNature.STOCK,410],
  ["AP","Accounts Payable",StatementType.BALANCE_SHEET,ValueNature.STOCK,420],
  ["SHORT_TERM_DEBT","Short-term Debt",StatementType.BALANCE_SHEET,ValueNature.STOCK,430],
  ["CURRENT_LIAB","Total Current Liabilities",StatementType.BALANCE_SHEET,ValueNature.STOCK,440],
  ["LONG_TERM_DEBT","Long-term Debt",StatementType.BALANCE_SHEET,ValueNature.STOCK,450],
  ["LEASE_LIABILITIES","Lease Liabilities",StatementType.BALANCE_SHEET,ValueNature.STOCK,460],
  ["TOTAL_DEBT","Total Debt",StatementType.BALANCE_SHEET,ValueNature.STOCK,470],
  ["TOTAL_LIAB","Total Liabilities",StatementType.BALANCE_SHEET,ValueNature.STOCK,480],
  ["EQUITY","Total Equity",StatementType.BALANCE_SHEET,ValueNature.STOCK,490],
  ["EQUITY_PARENT","Equity Attributable to Owners of Parent",StatementType.BALANCE_SHEET,ValueNature.STOCK,500],
  ["RETAINED_EARNINGS","Retained Earnings",StatementType.BALANCE_SHEET,ValueNature.STOCK,510],
  ["OCF","Operating Cash Flow",StatementType.CASH_FLOW,ValueNature.FLOW,600],
  ["CAPEX","Capital Expenditure",StatementType.CASH_FLOW,ValueNature.FLOW,610],
  ["ICF","Investing Cash Flow",StatementType.CASH_FLOW,ValueNature.FLOW,620],
  ["CFF","Financing Cash Flow",StatementType.CASH_FLOW,ValueNature.FLOW,630],
  ["DIVIDENDS_PAID","Dividends Paid",StatementType.CASH_FLOW,ValueNature.FLOW,640],
  ["DEBT_ISSUED","Debt Issued",StatementType.CASH_FLOW,ValueNature.FLOW,650],
  ["DEBT_REPAID","Debt Repaid",StatementType.CASH_FLOW,ValueNature.FLOW,660],
  ["FCF","Free Cash Flow",StatementType.CASH_FLOW,ValueNature.FLOW,670],
  ["NET_CHANGE_CASH","Net Change in Cash",StatementType.CASH_FLOW,ValueNature.FLOW,680],
];

const IAS1: Ref = { label: "IFRS Foundation — IAS 1 Presentation of Financial Statements", url: "https://www.ifrs.org/issued-standards/list-of-standards/ias-1-presentation-of-financial-statements/" };
const IAS2: Ref = { label: "IFRS Foundation — IAS 2 Inventories", url: "https://www.ifrs.org/issued-standards/list-of-standards/ias-2-inventories/" };
const IAS7: Ref = { label: "IFRS Foundation — IAS 7 Statement of Cash Flows", url: "https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-of-cash-flows/" };
const IAS12: Ref = { label: "IFRS Foundation — IAS 12 Income Taxes", url: "https://www.ifrs.org/issued-standards/list-of-standards/ias-12-income-taxes/" };
const IAS16: Ref = { label: "IFRS Foundation — IAS 16 Property, Plant and Equipment", url: "https://www.ifrs.org/issued-standards/list-of-standards/ias-16-property-plant-and-equipment/" };
const IAS23: Ref = { label: "IFRS Foundation — IAS 23 Borrowing Costs", url: "https://www.ifrs.org/issued-standards/list-of-standards/ias-23-borrowing-costs/" };
const IAS33: Ref = { label: "IFRS Foundation — IAS 33 Earnings per Share", url: "https://www.ifrs.org/issued-standards/list-of-standards/ias-33-earnings-per-share.html/" };
const IAS36: Ref = { label: "IFRS Foundation — IAS 36 Impairment of Assets", url: "https://www.ifrs.org/issued-standards/list-of-standards/ias-36-impairment-of-assets/" };
const IAS38: Ref = { label: "IFRS Foundation — IAS 38 Intangible Assets", url: "https://www.ifrs.org/issued-standards/list-of-standards/ias-38-intangible-assets/" };
const IFRS3: Ref = { label: "IFRS Foundation — IFRS 3 Business Combinations", url: "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-3-business-combinations/" };
const IFRS9: Ref = { label: "IFRS Foundation — IFRS 9 Financial Instruments", url: "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-9-financial-instruments/" };
const IFRS15: Ref = { label: "IFRS Foundation — IFRS 15 Revenue from Contracts with Customers", url: "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-15-revenue-from-contracts-with-customers/" };
const IFRS16: Ref = { label: "IFRS Foundation — IFRS 16 Leases", url: "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-16-leases/" };

const knowledge: Record<string, Knowledge> = {
  REV:{displayNameId:"Pendapatan / Penjualan",definition:"Pendapatan yang diakui dari penyerahan barang atau jasa kepada pelanggan dalam aktivitas utama perusahaan.",investorMeaning:"Fondasi pertumbuhan bisnis. Investor perlu memisahkan pertumbuhan yang berasal dari volume, harga, akuisisi, perubahan kurs, atau faktor sementara.",aliases:["pendapatan","penjualan","penjualan neto","net sales","sales","revenue"],relatedMetrics:["Revenue Growth","Revenue CAGR","Gross Margin","Receivable Days"],positiveSignals:["Revenue tumbuh konsisten bersama arus kas operasi.","Pertumbuhan disertai margin yang stabil atau membaik."],redFlags:["Revenue tumbuh tetapi piutang tumbuh jauh lebih cepat.","Pertumbuhan tinggi tidak diikuti gross profit atau operating cash flow."],sourceRefs:[IFRS15]},
  COGS:{displayNameId:"Beban Pokok Penjualan",definition:"Biaya yang secara langsung berkaitan dengan barang atau jasa yang menghasilkan pendapatan pada periode tersebut.",investorMeaning:"Menunjukkan economics dasar produk dan sangat menentukan gross margin.",aliases:["beban pokok penjualan","harga pokok penjualan","cost of sales","cost of goods sold","HPP"],relatedMetrics:["Gross Profit","Gross Margin","Inventory Turnover"],positiveSignals:["COGS tumbuh lebih lambat dari revenue sehingga gross margin membaik."],redFlags:["COGS tumbuh lebih cepat daripada revenue secara persisten.","Lonjakan COGS tidak dapat dijelaskan oleh volume atau harga bahan baku."],sourceRefs:[IAS2,IAS1]},
  GROSS_PROFIT:{displayNameId:"Laba Kotor",definition:"Selisih antara pendapatan dan beban pokok penjualan.",investorMeaning:"Ukuran awal pricing power, product mix, dan efisiensi produksi atau pengadaan.",aliases:["laba bruto","laba kotor","gross profit"],relatedMetrics:["Gross Margin","Revenue Growth"],positiveSignals:["Gross margin stabil atau meningkat bersama pertumbuhan revenue."],redFlags:["Revenue tumbuh tetapi gross margin terus turun.","Pemulihan laba hanya berasal dari pemotongan biaya di bawah gross profit."],sourceRefs:[IAS1]},
  SGA:{displayNameId:"Beban Penjualan, Umum & Administrasi",definition:"Beban operasional untuk fungsi penjualan, pemasaran, administrasi, dan fungsi korporat yang tidak termasuk beban pokok.",investorMeaning:"Menunjukkan operating leverage dan disiplin biaya overhead.",aliases:["beban penjualan","beban umum dan administrasi","SG&A","selling general administrative expense"],relatedMetrics:["SG&A / Revenue","Operating Margin","Operating Leverage"],positiveSignals:["SG&A tumbuh lebih lambat daripada revenue tanpa merusak kemampuan bisnis tumbuh."],redFlags:["SG&A tumbuh jauh lebih cepat dari revenue secara berulang.","Pemotongan SG&A ekstrem meningkatkan laba jangka pendek tetapi merusak penjualan atau kapabilitas bisnis."],sourceRefs:[IAS1]},
  OPERATING_PROFIT:{displayNameId:"Laba Operasi / EBIT",definition:"Laba yang dihasilkan aktivitas operasi sebelum dampak pembiayaan dan pajak.",investorMeaning:"Membantu menilai profitabilitas bisnis inti tanpa tercampur struktur pendanaan.",aliases:["laba usaha","laba operasi","operating profit","EBIT"],relatedMetrics:["Operating Margin","ROIC","Interest Coverage"],positiveSignals:["Operating profit tumbuh sejalan atau lebih cepat daripada revenue secara sehat."],redFlags:["Margin operasi turun terus meski revenue meningkat.","EBIT ditopang item satu kali yang tidak berasal dari operasi inti."],sourceRefs:[IAS1]},
  EBITDA:{displayNameId:"EBITDA",definition:"Ukuran kinerja sebelum bunga, pajak, depresiasi, dan amortisasi; biasanya merupakan non-GAAP/non-IFRS subtotal yang perlu direkonsiliasi.",investorMeaning:"Berguna untuk membandingkan kemampuan operasi sebelum struktur modal, tetapi tidak sama dengan cash flow karena mengabaikan modal kerja dan capex.",aliases:["EBITDA","earnings before interest tax depreciation amortization"],relatedMetrics:["EBITDA Margin","Debt / EBITDA","EV / EBITDA","OCF"],positiveSignals:["EBITDA tumbuh bersama revenue dan OCF."],redFlags:["EBITDA naik tetapi OCF memburuk.","Perusahaan menonjolkan adjusted EBITDA dengan terlalu banyak add-back berulang."],sourceRefs:[IAS1]},
  FINANCE_INCOME:{displayNameId:"Pendapatan Keuangan",definition:"Pendapatan dari aset keuangan atau aktivitas treasury, misalnya bunga atas deposito atau instrumen keuangan.",investorMeaning:"Dapat menambah laba tetapi biasanya bukan sumber utama economics operasional untuk perusahaan non-keuangan.",aliases:["pendapatan keuangan","pendapatan bunga","finance income","interest income"],relatedMetrics:["Finance Income / Pretax Profit","Cash Yield","Cash Balance"],positiveSignals:["Pendapatan keuangan berasal dari kelebihan likuiditas yang produktif dan tidak menutupi pelemahan bisnis inti."],redFlags:["Laba sangat bergantung pada pendapatan keuangan non-operasional.","Pendapatan keuangan melonjak karena item tidak berulang."],sourceRefs:[IFRS9,IAS1]},
  FINANCE_COST:{displayNameId:"Beban Keuangan",definition:"Biaya pembiayaan seperti bunga atas pinjaman dan kewajiban pembiayaan lainnya, dengan perlakuan tertentu atas borrowing costs yang memenuhi syarat kapitalisasi.",investorMeaning:"Menunjukkan beban struktur modal dan sensitivitas perusahaan terhadap suku bunga serta leverage.",aliases:["beban keuangan","beban bunga","finance cost","interest expense"],relatedMetrics:["Interest Coverage","Finance Cost / EBIT","Net Debt"],positiveSignals:["Beban bunga terkendali dan interest coverage membaik."],redFlags:["Finance cost naik jauh lebih cepat daripada EBIT.","Interest coverage turun mendekati level yang tidak aman."],sourceRefs:[IAS23,IAS1]},
  FX_GAIN_LOSS:{displayNameId:"Laba / Rugi Selisih Kurs",definition:"Dampak perubahan nilai tukar terhadap aset, liabilitas, pendapatan, atau beban yang berdenominasi mata uang asing.",investorMeaning:"Membantu mengidentifikasi sensitivitas laba terhadap kurs dan kecocokan natural hedge perusahaan.",aliases:["selisih kurs","laba rugi kurs","foreign exchange gain loss","FX gain loss"],relatedMetrics:["FX Gain/Loss / Pretax Profit","Foreign Currency Debt","Currency Exposure"],positiveSignals:["Eksposur kurs terkendali dan tidak mendominasi laba."],redFlags:["Rugi kurs besar terjadi berulang karena mismatch mata uang.","Profitabilitas sangat volatil akibat perubahan kurs."],sourceRefs:[IAS1]},
  PRETAX_PROFIT:{displayNameId:"Laba Sebelum Pajak",definition:"Laba setelah pendapatan dan beban operasi serta pembiayaan, tetapi sebelum beban pajak penghasilan.",investorMeaning:"Menghubungkan operating economics, struktur pembiayaan, dan dampak pajak.",aliases:["laba sebelum pajak","profit before tax","PBT","pretax profit"],relatedMetrics:["Pretax Margin","Effective Tax Rate","Operating Profit"],positiveSignals:["Pretax profit tumbuh sejalan dengan operating profit."],redFlags:["Pretax profit naik terutama karena keuntungan non-operasional sementara.","Gap antara EBIT dan pretax profit membesar karena beban pembiayaan."],sourceRefs:[IAS1]},
  TAX_EXPENSE:{displayNameId:"Beban Pajak Penghasilan",definition:"Beban pajak kini dan pajak tangguhan yang berkaitan dengan laba kena pajak sesuai ketentuan IAS 12.",investorMeaning:"Investor perlu menilai effective tax rate, sustainability manfaat pajak, dan perbedaan antara laba akuntansi dan laba kena pajak.",aliases:["beban pajak","pajak penghasilan","income tax expense","tax expense"],relatedMetrics:["Effective Tax Rate","Pretax Profit","Deferred Tax"],positiveSignals:["Effective tax rate relatif stabil dan dapat dijelaskan oleh bisnis."],redFlags:["Laba ditopang manfaat pajak yang tidak berulang.","Effective tax rate sangat volatil tanpa penjelasan yang memadai."],sourceRefs:[IAS12]},
  NET_PROFIT:{displayNameId:"Laba Bersih",definition:"Laba setelah seluruh pendapatan, beban, pembiayaan, dan pajak pada periode berjalan.",investorMeaning:"Ukuran akhir profitabilitas, tetapi kualitasnya harus dikonfirmasi dengan arus kas dan item non-recurring.",aliases:["laba tahun berjalan","laba bersih","net income","profit for the year","net profit"],relatedMetrics:["Net Margin","ROE","EPS","OCF / Net Profit"],positiveSignals:["Laba tumbuh bersama operating cash flow."],redFlags:["Laba naik tetapi OCF lemah atau negatif.","Laba banyak ditopang keuntungan satu kali."],sourceRefs:[IAS1]},
  NET_PROFIT_PARENT:{displayNameId:"Laba Bersih Pemilik Entitas Induk",definition:"Bagian laba konsolidasian yang dapat diatribusikan kepada pemegang saham entitas induk.",investorMeaning:"Lebih relevan bagi pemegang saham induk ketika grup memiliki kepentingan nonpengendali.",aliases:["laba yang dapat diatribusikan kepada pemilik entitas induk","profit attributable to owners of parent","net profit parent"],relatedMetrics:["EPS","ROE Parent","Net Profit Parent Growth"],positiveSignals:["Laba pemilik induk tumbuh bersama cash flow dan equity pemilik induk."],redFlags:["Laba konsolidasi tumbuh tetapi laba pemilik induk stagnan atau turun.","Porsi non-controlling interest menyerap peningkatan laba secara material."],sourceRefs:[IAS1]},
  EPS_BASIC:{displayNameId:"Laba per Saham Dasar",definition:"Laba yang tersedia bagi pemegang saham biasa dibagi rata-rata tertimbang jumlah saham biasa beredar sesuai IAS 33.",investorMeaning:"Mengukur pertumbuhan laba per lembar saham, bukan sekadar pertumbuhan laba total.",aliases:["laba per saham dasar","basic EPS","earnings per share"],relatedMetrics:["EPS Growth","P/E","Share Count"],positiveSignals:["EPS tumbuh sejalan atau lebih cepat dari laba bersih tanpa dilusi material."],redFlags:["Laba naik tetapi EPS stagnan karena penerbitan saham.","EPS naik terutama karena buyback besar yang dibiayai utang."],sourceRefs:[IAS33]},
  EPS_DILUTED:{displayNameId:"Laba per Saham Dilusian",definition:"EPS setelah memperhitungkan dampak instrumen berpotensi dilutif seperti opsi, waran, atau instrumen konversi sesuai IAS 33.",investorMeaning:"Menunjukkan potensi penurunan laba per saham jika instrumen dilutif menjadi saham biasa.",aliases:["laba per saham dilusian","diluted EPS","diluted earnings per share"],relatedMetrics:["Dilution","EPS Growth","Basic vs Diluted EPS"],positiveSignals:["Perbedaan diluted dan basic EPS kecil serta stabil."],redFlags:["Diluted EPS jauh di bawah basic EPS.","Potensi dilusi meningkat dari opsi, waran, atau convertible instruments."],sourceRefs:[IAS33]},
  CASH:{displayNameId:"Kas dan Setara Kas",definition:"Kas dan investasi jangka sangat pendek yang sangat likuid dan mudah dikonversi menjadi jumlah kas yang diketahui.",investorMeaning:"Bantalan likuiditas yang perlu dibandingkan dengan utang, kebutuhan modal kerja, dan kualitas cash generation.",aliases:["kas","kas dan setara kas","cash","cash equivalents"],relatedMetrics:["Net Debt","Current Ratio","Cash Runway"],positiveSignals:["Kas memadai dibanding kewajiban jangka pendek dan kebutuhan operasi."],redFlags:["Kas turun cepat sementara utang meningkat.","Kas besar tetapi sebagian besar restricted atau tidak tersedia untuk induk."],sourceRefs:[IAS7]},
  SHORT_TERM_INVESTMENTS:{displayNameId:"Investasi Jangka Pendek",definition:"Instrumen investasi berjangka pendek yang biasanya dikelola sebagai bagian dari likuiditas atau treasury dan tidak selalu memenuhi definisi cash equivalent.",investorMeaning:"Menambah sumber likuiditas, tetapi risiko nilai dan tingkat likuiditas harus diperiksa.",aliases:["investasi jangka pendek","short-term investments","marketable securities","time deposits"],relatedMetrics:["Cash + Short-term Investments","Current Ratio","Liquidity"],positiveSignals:["Instrumen likuid, berkualitas tinggi, dan mudah dimonetisasi."],redFlags:["Investasi besar berada pada instrumen berisiko atau tidak likuid.","Nilai investasi turun atau konsentrasi pada pihak tertentu terlalu tinggi."],sourceRefs:[IFRS9]},
  AR:{displayNameId:"Piutang Usaha",definition:"Hak kontraktual perusahaan untuk menerima kas dari pelanggan atas barang atau jasa yang telah diberikan.",investorMeaning:"Menguji kualitas pertumbuhan penjualan dan kemampuan perusahaan menagih pelanggan.",aliases:["piutang usaha","piutang dagang","trade receivables","accounts receivable","receivables"],relatedMetrics:["Receivable Days / DSO","Cash Conversion Cycle","OCF vs Net Profit","Allowance / ECL"],positiveSignals:["Piutang tumbuh sejalan atau lebih lambat dari revenue.","DSO stabil atau membaik."],redFlags:["Piutang tumbuh jauh lebih cepat daripada revenue.","DSO meningkat terus atau allowance/ECL melonjak."],sourceRefs:[IFRS9]},
  OTHER_RECEIVABLES:{displayNameId:"Piutang Lain-lain",definition:"Piutang di luar piutang usaha utama, misalnya klaim, uang muka yang dapat ditagih, atau saldo lain yang memenuhi definisi aset keuangan.",investorMeaning:"Perlu dibedah karena saldo yang terlalu besar atau tidak jelas dapat menyembunyikan kualitas aset yang lebih rendah.",aliases:["piutang lain-lain","other receivables","other accounts receivable"],relatedMetrics:["Other Receivables / Assets","Receivable Growth","ECL"],positiveSignals:["Saldo kecil, stabil, dan memiliki penjelasan ekonomi yang jelas."],redFlags:["Piutang lain-lain melonjak tanpa penjelasan bisnis.","Saldo material kepada pihak berelasi atau lama tidak tertagih."],sourceRefs:[IFRS9]},
  INV:{displayNameId:"Persediaan",definition:"Aset berupa barang untuk dijual, dalam proses produksi, atau bahan dan perlengkapan untuk produksi atau pemberian jasa.",investorMeaning:"Menunjukkan modal yang tertahan dalam stok, permintaan, efisiensi supply chain, dan risiko obsolete.",aliases:["persediaan","inventory","inventories","stok"],relatedMetrics:["Inventory Days","Inventory Turnover","Cash Conversion Cycle","Gross Margin"],positiveSignals:["Inventory tumbuh sejalan dengan penjualan dan turnover stabil."],redFlags:["Inventory naik jauh lebih cepat dari revenue.","Inventory days meningkat terus atau write-down persediaan membesar."],sourceRefs:[IAS2]},
  CURRENT_ASSETS:{displayNameId:"Total Aset Lancar",definition:"Total aset yang diperkirakan direalisasikan, dijual, dikonsumsi, atau menjadi kas dalam siklus operasi normal atau jangka pendek sesuai klasifikasi laporan keuangan.",investorMeaning:"Menunjukkan sumber daya jangka pendek untuk mendukung modal kerja dan kewajiban lancar.",aliases:["aset lancar","total current assets","current assets"],relatedMetrics:["Current Ratio","Quick Ratio","Working Capital"],positiveSignals:["Aset lancar berkualitas dan cukup untuk kebutuhan modal kerja."],redFlags:["Aset lancar naik terutama karena piutang atau inventory yang menumpuk.","Current ratio terlihat baik tetapi kas sebenarnya rendah."],sourceRefs:[IAS1]},
  PPE:{displayNameId:"Aset Tetap / Properti, Pabrik dan Peralatan",definition:"Aset berwujud yang digunakan untuk produksi, jasa, penyewaan, atau administrasi lebih dari satu periode.",investorMeaning:"Penting untuk bisnis padat modal; pertumbuhan PPE harus dinilai bersama utilisasi, revenue, capex, dan ROIC.",aliases:["aset tetap","property plant equipment","PPE","fixed assets"],relatedMetrics:["Asset Turnover","ROIC","CAPEX / Sales","Depreciation"],positiveSignals:["Investasi aset menghasilkan pertumbuhan kapasitas, revenue, dan return yang memadai."],redFlags:["PPE/capex besar tetapi utilisasi, revenue, atau ROIC tidak membaik.","Impairment aset berulang menunjukkan investasi masa lalu tidak produktif."],sourceRefs:[IAS16,IAS36]},
  RIGHT_OF_USE_ASSETS:{displayNameId:"Aset Hak Guna",definition:"Aset yang merepresentasikan hak lessee untuk menggunakan aset pendasar selama masa sewa.",investorMeaning:"Membantu melihat aset ekonomi dari kontrak sewa dan fixed commitments yang terkait.",aliases:["aset hak guna","right-of-use asset","ROU asset"],relatedMetrics:["Lease Liabilities","Adjusted Debt","EBITDA"],positiveSignals:["Aset sewa mendukung operasi dan kewajiban sewanya sejalan dengan cash flow."],redFlags:["Aset hak guna dan kewajiban sewa meningkat cepat tanpa pertumbuhan operasi.","Bisnis semakin bergantung pada fixed lease commitments saat cash flow melemah."],sourceRefs:[IFRS16]},
  GOODWILL:{displayNameId:"Goodwill",definition:"Aset yang timbul dalam kombinasi bisnis dan merepresentasikan manfaat ekonomi masa depan yang tidak dapat diidentifikasi secara individual.",investorMeaning:"Sering mencerminkan premi akuisisi; kualitasnya harus diuji melalui performa bisnis yang diakuisisi dan impairment test.",aliases:["goodwill","muhibah"],relatedMetrics:["Goodwill / Equity","ROIC","Acquisition Return","Impairment"],positiveSignals:["Bisnis hasil akuisisi menghasilkan cash flow dan return sesuai ekspektasi."],redFlags:["Goodwill sangat besar terhadap equity.","Akuisisi berulang diikuti impairment besar atau ROIC menurun."],sourceRefs:[IFRS3,IAS36]},
  INTANGIBLE_ASSETS:{displayNameId:"Aset Takberwujud",definition:"Aset nonmoneter teridentifikasi tanpa wujud fisik yang memenuhi kriteria pengakuan.",investorMeaning:"Investor perlu membedakan aset produktif seperti lisensi atau software dari kapitalisasi biaya yang dapat menunda pengakuan expense.",aliases:["aset takberwujud","aset tidak berwujud","intangible assets","software","license"],relatedMetrics:["ROIC","Amortisation","Intangible Assets / Equity"],positiveSignals:["Aset intangible mendukung pertumbuhan cash flow dan return."],redFlags:["Kapitalisasi intangible meningkat cepat sementara cash flow lemah.","Impairment atau write-off intangible terjadi berulang."],sourceRefs:[IAS38,IAS36]},
  LONG_TERM_INVESTMENTS:{displayNameId:"Investasi Jangka Panjang",definition:"Investasi yang dimiliki untuk horizon lebih panjang, termasuk instrumen keuangan atau kepentingan investasi tertentu sesuai klasifikasi yang berlaku.",investorMeaning:"Perlu dinilai berdasarkan return, likuiditas, tujuan strategis, dan risiko penurunan nilai.",aliases:["investasi jangka panjang","long-term investments","non-current investments"],relatedMetrics:["Investment Return","ROIC","Impairment","Investment / Assets"],positiveSignals:["Investasi menghasilkan return atau nilai strategis yang terukur."],redFlags:["Investasi besar berulang tidak menghasilkan cash return.","Penurunan nilai investasi atau konsentrasi pada aset berisiko meningkat."],sourceRefs:[IFRS9,IAS36]},
  TOTAL_ASSETS:{displayNameId:"Total Aset",definition:"Jumlah seluruh aset lancar dan tidak lancar yang diakui pada tanggal laporan posisi keuangan.",investorMeaning:"Menunjukkan skala resources perusahaan; kualitas pertumbuhan aset harus dikaitkan dengan revenue, laba, cash flow, dan return.",aliases:["total aset","jumlah aset","total assets"],relatedMetrics:["ROA","Asset Turnover","Asset Growth"],positiveSignals:["Pertumbuhan aset diikuti pertumbuhan revenue, laba, dan cash flow."],redFlags:["Aset tumbuh cepat tetapi ROA atau asset turnover terus turun.","Pertumbuhan aset terutama berasal dari goodwill, piutang, atau aset berisiko."],sourceRefs:[IAS1]},
  AP:{displayNameId:"Utang Usaha",definition:"Kewajiban kepada pemasok atas barang atau jasa yang telah diterima dalam aktivitas operasi normal dan belum dibayar.",investorMeaning:"Membantu menilai manajemen modal kerja, posisi tawar terhadap pemasok, dan potensi tekanan likuiditas.",aliases:["utang usaha","utang dagang","accounts payable","trade payables","AP"],relatedMetrics:["Payable Days / DPO","Cash Conversion Cycle","Working Capital"],positiveSignals:["Utang usaha tumbuh sejalan dengan aktivitas operasi dan payable days stabil."],redFlags:["Payable days melonjak tajam karena pembayaran pemasok tertunda.","Utang usaha tumbuh jauh lebih cepat daripada inventory atau COGS saat kas melemah."],sourceRefs:[IFRS9,IAS1]},
  SHORT_TERM_DEBT:{displayNameId:"Utang Jangka Pendek",definition:"Pinjaman dan kewajiban pembiayaan yang jatuh tempo dalam jangka pendek atau diklasifikasikan sebagai current liability.",investorMeaning:"Menunjukkan refinancing risk dan kebutuhan likuiditas yang paling dekat.",aliases:["utang jangka pendek","pinjaman jangka pendek","short-term debt","current borrowings"],relatedMetrics:["Short-term Debt / Cash","Current Ratio","Net Debt","Interest Coverage"],positiveSignals:["Kas dan OCF memadai untuk menutup jatuh tempo jangka pendek."],redFlags:["Utang jangka pendek melonjak sementara kas dan OCF melemah.","Perusahaan bergantung pada rollover utang untuk bertahan."],sourceRefs:[IFRS9,IAS1]},
  CURRENT_LIAB:{displayNameId:"Total Liabilitas Jangka Pendek",definition:"Total kewajiban yang diperkirakan diselesaikan dalam siklus operasi normal atau jangka pendek sesuai klasifikasi current liabilities.",investorMeaning:"Menunjukkan beban kewajiban jangka dekat yang harus dilayani oleh aset lancar dan cash generation.",aliases:["liabilitas jangka pendek","kewajiban lancar","current liabilities","total current liabilities"],relatedMetrics:["Current Ratio","Quick Ratio","Working Capital"],positiveSignals:["Liabilitas lancar terkelola dengan likuiditas dan cash conversion yang sehat."],redFlags:["Liabilitas lancar tumbuh jauh lebih cepat daripada aset lancar berkualitas.","Working capital negatif memburuk tanpa model bisnis yang memang mendukungnya."],sourceRefs:[IAS1]},
  LONG_TERM_DEBT:{displayNameId:"Utang Jangka Panjang",definition:"Pinjaman dan kewajiban pembiayaan yang jatuh tempo lebih panjang dari klasifikasi current liability.",investorMeaning:"Menunjukkan leverage struktural dan kewajiban pembayaran bunga serta pokok pada masa depan.",aliases:["utang jangka panjang","pinjaman jangka panjang","long-term debt","non-current borrowings"],relatedMetrics:["Debt / EBITDA","Interest Coverage","Net Debt","Debt Maturity"],positiveSignals:["Utang jangka panjang mendanai aset produktif dan leverage terkendali."],redFlags:["Utang naik tanpa pertumbuhan EBITDA atau OCF yang sepadan.","Maturity wall besar mendekat saat kondisi pendanaan memburuk."],sourceRefs:[IFRS9,IAS1]},
  LEASE_LIABILITIES:{displayNameId:"Liabilitas Sewa",definition:"Kewajiban lessee untuk melakukan pembayaran sewa yang diakui berdasarkan IFRS 16.",investorMeaning:"Secara ekonomi merupakan fixed commitment yang perlu dipertimbangkan dalam adjusted leverage.",aliases:["liabilitas sewa","lease liabilities","lease obligation"],relatedMetrics:["Lease Liabilities / EBITDA","Adjusted Debt","Fixed Charge Coverage"],positiveSignals:["Liabilitas sewa sejalan dengan aset produktif dan kemampuan cash flow."],redFlags:["Komitmen sewa meningkat cepat saat operasi melemah.","Adjusted leverage jauh lebih tinggi setelah memasukkan lease liabilities."],sourceRefs:[IFRS16]},
  TOTAL_DEBT:{displayNameId:"Total Utang Berbunga",definition:"Agregasi kewajiban pembiayaan berbunga jangka pendek dan jangka panjang yang digunakan InvestAI untuk analisis leverage.",investorMeaning:"Menentukan risiko finansial dan sensitivitas terhadap suku bunga, refinancing, dan penurunan cash flow.",aliases:["total debt","utang berbunga","pinjaman","borrowings","bank loans"],relatedMetrics:["Net Debt","Debt / EBITDA","Debt / Equity","Interest Coverage"],positiveSignals:["Debt tumbuh lebih lambat daripada OCF atau EBITDA dan leverage menurun."],redFlags:["Debt naik cepat saat OCF melemah.","Leverage tinggi tetapi interest coverage menurun."],sourceRefs:[IFRS9]},
  TOTAL_LIAB:{displayNameId:"Total Liabilitas",definition:"Jumlah seluruh kewajiban lancar dan tidak lancar yang diakui pada tanggal laporan posisi keuangan.",investorMeaning:"Menunjukkan total claims pihak lain terhadap aset perusahaan dan membantu membaca struktur pendanaan.",aliases:["total liabilitas","jumlah kewajiban","total liabilities"],relatedMetrics:["Liabilities / Assets","Debt / Equity","Equity Ratio"],positiveSignals:["Pertumbuhan liabilitas lebih lambat daripada aset produktif dan cash flow."],redFlags:["Liabilitas tumbuh cepat sementara equity atau cash flow melemah.","Porsi kewajiban berisiko tinggi atau jangka pendek meningkat."],sourceRefs:[IAS1]},
  EQUITY:{displayNameId:"Total Ekuitas",definition:"Residual interest dalam aset setelah dikurangi seluruh liabilitas.",investorMeaning:"Mencerminkan book capital pemegang saham dan menjadi denominator penting untuk ROE serta leverage.",aliases:["ekuitas","total equity","shareholders equity"],relatedMetrics:["ROE","Debt / Equity","Book Value Growth"],positiveSignals:["Ekuitas tumbuh terutama dari laba ditahan dengan ROE sehat."],redFlags:["Ekuitas turun akibat rugi atau impairment berulang.","Ekuitas tumbuh terutama karena penerbitan saham, bukan akumulasi laba."],sourceRefs:[IAS1]},
  EQUITY_PARENT:{displayNameId:"Ekuitas Pemilik Entitas Induk",definition:"Bagian ekuitas konsolidasian yang dapat diatribusikan kepada pemegang saham entitas induk setelah memisahkan non-controlling interests.",investorMeaning:"Lebih tepat untuk mengukur book value dan ROE yang benar-benar menjadi hak pemegang saham induk.",aliases:["ekuitas pemilik entitas induk","equity attributable to owners of parent","parent equity"],relatedMetrics:["Book Value per Share","ROE Parent","Equity Growth"],positiveSignals:["Ekuitas pemilik induk tumbuh bersama laba yang dapat diatribusikan kepada induk."],redFlags:["Ekuitas konsolidasi naik tetapi bagian pemilik induk turun.","Dilusi atau transaksi korporasi mengurangi book value per share."],sourceRefs:[IAS1]},
  RETAINED_EARNINGS:{displayNameId:"Saldo Laba",definition:"Akumulasi laba setelah memperhitungkan distribusi kepada pemegang saham dan penyesuaian relevan yang tetap berada dalam ekuitas.",investorMeaning:"Menunjukkan kemampuan perusahaan menahan dan menginvestasikan kembali laba sepanjang waktu.",aliases:["saldo laba","laba ditahan","retained earnings"],relatedMetrics:["Retained Earnings Growth","ROE","Dividend Payout"],positiveSignals:["Saldo laba tumbuh konsisten dan reinvestasi menghasilkan return yang baik."],redFlags:["Saldo laba menurun terus karena rugi.","Perusahaan menahan banyak laba tetapi ROIC atau pertumbuhan tetap rendah."],sourceRefs:[IAS1]},
  OCF:{displayNameId:"Arus Kas Operasi",definition:"Arus kas dari aktivitas penghasil pendapatan utama perusahaan dan aktivitas lain yang bukan investasi atau pendanaan.",investorMeaning:"Salah satu pemeriksaan terpenting atas kualitas laba karena menunjukkan kas yang benar-benar dihasilkan operasi.",aliases:["arus kas operasi","cash flow from operations","operating cash flow","CFO","OCF"],relatedMetrics:["OCF / Net Profit","Cash Conversion","Free Cash Flow","Cash Conversion Cycle"],positiveSignals:["OCF konsisten positif dan sejalan atau lebih kuat daripada laba."],redFlags:["Net profit positif tetapi OCF terus lemah atau negatif.","OCF membaik hanya karena penundaan pembayaran pemasok atau pelepasan modal kerja sementara."],sourceRefs:[IAS7]},
  CAPEX:{displayNameId:"Belanja Modal / Capital Expenditure",definition:"Pengeluaran untuk memperoleh atau meningkatkan aset jangka panjang; InvestAI menurunkannya terutama dari cash outflow investasi terkait PPE atau intangible.",investorMeaning:"Perlu dibedakan secara konseptual antara maintenance dan growth capex untuk menilai reinvestasi dan FCF.",aliases:["belanja modal","capital expenditure","capex","purchase of fixed assets","acquisition of PPE"],relatedMetrics:["CAPEX / Sales","FCF","Asset Turnover","ROIC"],positiveSignals:["Capex menghasilkan pertumbuhan kapasitas dan return di atas cost of capital."],redFlags:["Capex tinggi berulang tetapi revenue, OCF, atau ROIC stagnan.","Maintenance capex tampak diremehkan sehingga FCF terlihat terlalu tinggi."],sourceRefs:[IAS7,IAS16]},
  ICF:{displayNameId:"Arus Kas Investasi",definition:"Arus kas yang berkaitan dengan perolehan dan pelepasan aset jangka panjang serta investasi lain yang bukan cash equivalents.",investorMeaning:"Menunjukkan bagaimana perusahaan mengalokasikan kas untuk capex, akuisisi, investasi, atau pelepasan aset.",aliases:["arus kas investasi","cash flow from investing activities","investing cash flow","ICF"],relatedMetrics:["CAPEX","Acquisition Spend","Asset Sales","FCF"],positiveSignals:["Cash outflow investasi terutama menuju aset dengan return yang memadai."],redFlags:["Cash outflow investasi besar berulang tanpa perbaikan revenue atau ROIC.","Perusahaan menjual aset terus-menerus untuk menopang kas."],sourceRefs:[IAS7]},
  CFF:{displayNameId:"Arus Kas Pendanaan",definition:"Arus kas yang menyebabkan perubahan ukuran dan komposisi modal serta borrowings perusahaan.",investorMeaning:"Menunjukkan apakah perusahaan menambah utang/equity, membayar utang, buyback, atau membayar dividen.",aliases:["arus kas pendanaan","cash flow from financing activities","financing cash flow","CFF"],relatedMetrics:["Debt Issued","Debt Repaid","Dividends","Share Issuance"],positiveSignals:["Struktur pendanaan mendukung kebutuhan bisnis tanpa meningkatkan risiko secara berlebihan."],redFlags:["Perusahaan terus bergantung pada utang atau penerbitan saham untuk menutup operasi.","CFF positif besar sementara OCF negatif berkepanjangan."],sourceRefs:[IAS7]},
  DIVIDENDS_PAID:{displayNameId:"Dividen Dibayar",definition:"Arus kas keluar kepada pemegang saham dalam bentuk dividen yang dibayarkan selama periode.",investorMeaning:"Menunjukkan cash return kepada pemegang saham dan harus diuji terhadap laba, OCF, dan FCF.",aliases:["dividen dibayar","pembayaran dividen","dividends paid","cash dividends"],relatedMetrics:["Dividend Payout","FCF Coverage","Dividend Yield"],positiveSignals:["Dividen ditopang oleh FCF dan payout ratio berkelanjutan."],redFlags:["Dividen dibiayai dengan utang baru.","Dividen dipertahankan saat FCF negatif dan likuiditas melemah."],sourceRefs:[IAS7]},
  DEBT_ISSUED:{displayNameId:"Penerbitan / Penarikan Utang",definition:"Kas masuk yang berasal dari pinjaman atau instrumen utang baru selama periode.",investorMeaning:"Perlu dinilai berdasarkan tujuan penggunaan dana dan dampaknya pada leverage serta return.",aliases:["penarikan utang","penerimaan pinjaman","debt issued","proceeds from borrowings"],relatedMetrics:["Net Debt","Debt / EBITDA","ROIC","Debt Maturity"],positiveSignals:["Utang baru mendanai investasi produktif atau refinancing dengan terms lebih baik."],redFlags:["Utang baru berulang digunakan menutup kekurangan OCF.","Debt issuance meningkat sementara leverage sudah tinggi."],sourceRefs:[IAS7,IFRS9]},
  DEBT_REPAID:{displayNameId:"Pembayaran Utang",definition:"Kas keluar untuk membayar pokok pinjaman atau instrumen utang selama periode.",investorMeaning:"Menunjukkan deleveraging dan kemampuan perusahaan memenuhi kewajiban dari cash generation.",aliases:["pembayaran utang","pelunasan pinjaman","debt repaid","repayment of borrowings"],relatedMetrics:["Net Debt","FCF","Debt Maturity","Liquidity"],positiveSignals:["Pembayaran utang menurunkan leverage tanpa mengganggu kebutuhan operasi."],redFlags:["Pembayaran utang menguras kas karena FCF tidak mencukupi.","Utang dibayar hanya dengan menerbitkan utang baru lain."],sourceRefs:[IAS7,IFRS9]},
  FCF:{displayNameId:"Arus Kas Bebas / Free Cash Flow",definition:"Metrik analitis InvestAI yang umumnya dihitung dari OCF dikurangi capex; FCF bukan subtotal wajib IFRS sehingga formula harus ditampilkan transparan.",investorMeaning:"Menunjukkan kas yang tersisa setelah kebutuhan investasi utama dan dapat digunakan untuk utang, dividen, buyback, akuisisi, atau ekspansi.",aliases:["free cash flow","arus kas bebas","FCF"],relatedMetrics:["FCF Margin","FCF Yield","OCF","CAPEX"],positiveSignals:["FCF positif dan bertumbuh secara berkelanjutan."],redFlags:["Laba meningkat tetapi FCF negatif berkepanjangan tanpa alasan ekspansi ber-return tinggi.","FCF tampak tinggi karena capex sementara ditunda."],sourceRefs:[IAS7]},
  NET_CHANGE_CASH:{displayNameId:"Perubahan Bersih Kas",definition:"Perubahan total kas dan setara kas selama periode setelah arus kas operasi, investasi, pendanaan, dan efek lain yang relevan.",investorMeaning:"Membantu melihat sumber kenaikan atau penurunan kas, tetapi harus diurai berdasarkan OCF, ICF, dan CFF.",aliases:["perubahan bersih kas","net change in cash","net increase decrease in cash"],relatedMetrics:["OCF","ICF","CFF","Ending Cash"],positiveSignals:["Kas meningkat terutama dari OCF yang sehat."],redFlags:["Kas meningkat hanya karena utang atau penerbitan saham baru.","Kas terus turun akibat operasi negatif atau investasi tanpa return."],sourceRefs:[IAS7]},
};

async function main() {
  const missing = accounts.map(([code]) => code).filter((code) => !knowledge[code]);
  if (missing.length > 0) throw new Error(`Investor dictionary incomplete: ${missing.join(", ")}`);

  for (const [code,name,statementType,valueNature,sortOrder] of accounts) {
    const k = knowledge[code];
    await prisma.canonicalAccount.upsert({
      where:{code},
      update:{name,statementType,valueNature,sortOrder,isActive:true,...k},
      create:{code,name,statementType,valueNature,sortOrder,...k},
    });
  }

  for (const company of [
    {ticker:"ICBP",name:"Indofood CBP Sukses Makmur Tbk",sector:"Consumer Non-Cyclicals",subsector:"Processed Foods"},
    {ticker:"BTPS",name:"Bank BTPN Syariah Tbk",sector:"Financials",subsector:"Banks"},
    {ticker:"SMRA",name:"Summarecon Agung Tbk",sector:"Properties",subsector:"Real Estate"},
    {ticker:"MEDC",name:"Medco Energi Internasional Tbk",sector:"Energy",subsector:"Oil & Gas",currency:"USD"},
    {ticker:"POWR",name:"Cikarang Listrindo Tbk",sector:"Utilities",subsector:"Independent Power Producer"},
  ]) await prisma.company.upsert({where:{ticker:company.ticker},update:company,create:company});

  console.log(`Seeded ${accounts.length} canonical accounts with complete 46/46 investor dictionary coverage.`);
}

main().catch((e)=>{console.error(e);process.exit(1)}).finally(()=>prisma.$disconnect());